### ISSUE TITLE
RuntimeError: CUDNN_STATUS_MAPPING_ERROR

### ISSUE THREAD

**Issue by jeya-maria-jose** [hfslyc/AdvSemiSeg#8] opened 2018-05-25 12:48 UTC
Hey , 
When I try to validate the results , I am getting this error

```
  output = model(Variable(image, volatile=True).cuda(gpu0))
Traceback (most recent call last):
  File "evaluate_voc.py", line 235, in <module>
    main()
  File "evaluate_voc.py", line 214, in main
    output = model(Variable(image, volatile=True).cuda(gpu0))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/summer_interns/jose/AdvSemiSeg/model/deeplab.py", line 167, in forward
    x = self.conv1(x)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDNN_STATUS_MAPPING_ERROR

```

**Comment by hfslyc** [comment] 2018-05-25 17:10
Hi,

Which pytorch/python version are you using? The error looks like the input variable and model variable are not on the same GPU.

Can you print out `next(model.parameters()).get_device()` before the forward and verify the device id is the same with args.gpu which is one of your input?

**Comment by hfslyc** [comment] 2018-06-14 23:28
close this issue for now

**Closed as completed by hfslyc** 2018-06-14 23:28 UTC

**Comment by yuzhiguo07** [comment] 2018-07-07 02:35
I think the problem is that your GPU is too old to supported by PyTorch. I got the same error before and I notice that there was an UserWarning in the middle part of my log. It was solved after I changed my GPU from K420 to GTX1050Ti.

**Comment by jeya-maria-jose** [comment] 2018-07-07 11:48
Yeah. you are right , that was the issue!

**Comment by hfslyc** [comment] 2018-07-09 20:36
@xiaozhi0689 thanks for the clarification! 

@jeya-maria-jose I'm glad that you have solve the issue :)
